server:
  port: 8088

security:
  user:
    name: user
    password: pass
  
spring:
  zipkin:
    service:
      name: first-sample
    base-url: http://localhost:8080/
  sleuth:
    sampler:
      percentage: 1.0
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRE_SQL_USERNAME}
    password: ${POSTGRE_SQL_PASS}